[tool.poetry]
name = "learn-pytorch"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.10"
ipython = "^8.2.0"
numpy = "^1.22.3"
torch = "^1.11.0"
torchvision = "^0.12.0"
torchaudio = "^0.11.0"
